# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b118b57d1bd2a3df10bdbb7074ebd7b7b51d47f16b708f7d77dbc72146653e0c6031fb55d67ab17be0e4602d8da04e1921254f27b65962f0bc64c95396ae89c3

test:
  secret_key_base: bc8cbebb337058eb62133b122cb3c93a03d072a51e0790eab611cc9f349b83aa2457e5d025b1263dfcde93a2a78c29efde3daf0c101a3011612a9a2080600b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 'your secret key base'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"]%>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"]%>


test:
production:
  secret_key_base: 'your secret key base'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"]%>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"]
